<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body style="background: linear-gradient(180deg, #E5ABB5 0%, #DA3333 100%); background-repeat: no-repeat; background-size: cover;">
	<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div>
	<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div>
	<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div>
	<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div>
	<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div>
	<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div>
	<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div>
	<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div>
	<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div>
	<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div>
	<div>AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA</div>
	
</body>
</html>